import { Geist, Geist_Mono } from "next/font/google";
import { Poppins, Nosifer, Anton_SC, Chewy  } from "next/font/google";
import "./globals.css";

const nosifer = Nosifer({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: "--font-nosrif"
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // adjust as needed
  display: 'swap',
  variable: "--font-poppins"
})

const antonSC = Anton_SC({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: "--font-anton"
})

const chewy = Chewy({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: "--font-chewy"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nosifer.variable} ${chewy.variable} ${poppins.variable} ${antonSC.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
